"""
macOS 主题生成器 - 基于设计系统生成统一 QSS 样式
"""
from design_system import (
    TypographySystem, SpacingSystem, BorderRadiusSystem,
    ColorPalette, ShadowSystem, AnimationTokens
)


def generate_macos_theme():
    """生成完整的 macOS 风格主题样式表"""

    T = TypographySystem
    S = SpacingSystem
    R = BorderRadiusSystem
    C = ColorPalette
    SH = ShadowSystem
    A = AnimationTokens

    return f"""
    /* ============================================
       macOS Design System - Global Styles
       Generated by Theme Generator
       ============================================ */

    /* 全局基础样式 */
    QMainWindow, QWidget {{
        background-color: {C.BG_MAIN};
        color: {C.TEXT_PRIMARY};
        font-family: {T.FONT_FAMILY};
        font-size: {T.SIZE_BASE}px;
        font-weight: {T.WEIGHT_REGULAR};
    }}

    /* 标题文字层级 */
    QLabel[role="page-title"] {{
        font-size: {T.SIZE_2XL}px;
        font-weight: {T.WEIGHT_BOLD};
        color: {C.TEXT_PRIMARY};
        letter-spacing: -0.5px;
    }}

    QLabel[role="section-title"] {{
        font-size: {T.SIZE_XL}px;
        font-weight: {T.WEIGHT_SEMIBOLD};
        color: {C.TEXT_PRIMARY};
    }}

    QLabel[role="card-title"] {{
        font-size: {T.SIZE_LG}px;
        font-weight: {T.WEIGHT_MEDIUM};
        color: {C.TEXT_PRIMARY};
    }}

    QLabel[role="body"] {{
        font-size: {T.SIZE_BASE}px;
        font-weight: {T.WEIGHT_REGULAR};
        color: {C.TEXT_PRIMARY};
        line-height: {T.LINE_HEIGHT_BASE};
    }}

    QLabel[role="caption"] {{
        font-size: {T.SIZE_SM}px;
        font-weight: {T.WEIGHT_REGULAR};
        color: {C.TEXT_SECONDARY};
    }}

    QLabel[role="helper"] {{
        font-size: {T.SIZE_XS}px;
        font-weight: {T.WEIGHT_REGULAR};
        color: {C.TEXT_MUTED};
    }}

    /* 按钮系统 - Primary */
    QPushButton {{
        background-color: {C.PRIMARY};
        color: white;
        border: none;
        border-radius: {R.MD}px;
        padding: {S.SM}px {S.LG}px;
        font-size: {T.SIZE_BASE}px;
        font-weight: {T.WEIGHT_MEDIUM};
        font-family: {T.FONT_FAMILY};
        min-height: 34px;
    }}

    QPushButton:hover {{
        background-color: {C.PRIMARY_HOVER};
    }}

    QPushButton:pressed {{
        background-color: {C.PRIMARY_ACTIVE};
    }}

    QPushButton:disabled {{
        background-color: {C.GRAY_300};
        color: {C.GRAY_500};
    }}

    /* 次要按钮 */
    QPushButton[class="secondary"] {{
        background-color: transparent;
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
    }}

    QPushButton[class="secondary"]:hover {{
        background-color: {C.BG_SIDEBAR};
        border-color: {C.BORDER_STRONG};
    }}

    /* 危险按钮 */
    QPushButton[class="danger"] {{
        background-color: {C.ERROR};
    }}

    QPushButton[class="danger"]:hover {{
        background-color: #E5352B;
    }}

    /* 成功按钮 */
    QPushButton[class="success"] {{
        background-color: {C.SUCCESS};
    }}

    QPushButton[class="success"]:hover {{
        background-color: #2DB84D;
    }}

    /* 输入框系统 */
    QLineEdit {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
        border-radius: {R.MD}px;
        padding: {S.SM}px {S.MD}px;
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        min-height: 36px;
    }}

    QLineEdit:focus {{
        border: 2px solid {C.PRIMARY};
        background-color: white;
    }}

    QLineEdit:disabled {{
        background-color: {C.GRAY_100};
        color: {C.TEXT_MUTED};
        border-color: {C.BORDER_LIGHT};
    }}

    QLineEdit::placeholder {{
        color: {C.TEXT_MUTED};
    }}

    /* 文本域 */
    QTextEdit {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
        border-radius: {R.MD}px;
        padding: {S.SM}px;
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
    }}

    QTextEdit:focus {{
        border: 2px solid {C.PRIMARY};
    }}

    /* 下拉选择框 */
    QComboBox {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
        border-radius: {R.MD}px;
        padding: {S.SM}px {S.MD}px;
        font-size: {T.SIZE_BASE}px;
        font-weight: {T.WEIGHT_MEDIUM};
        font-family: {T.FONT_FAMILY};
        min-height: 36px;
    }}

    QComboBox:hover {{
        border-color: {C.BORDER_STRONG};
    }}

    QComboBox:focus {{
        border: 2px solid {C.PRIMARY};
    }}

    QComboBox::drop-down {{
        border: none;
        width: 28px;
        subcontrol-origin: padding;
        subcontrol-position: center right;
    }}

    QComboBox::down-arrow {{
        image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iOCIgdmlld0JveD0iMCAwIDEyIDgiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTEgMUw2IDZMMTEgMSIgc3Ryb2tlPSIjOEU4RTkzIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjwvc3ZnPg==);
        width: 12px;
        height: 8px;
    }}

    QComboBox QAbstractItemView {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
        border-radius: {R.MD}px;
        selection-background-color: {C.PRIMARY_BG};
        selection-color: {C.PRIMARY};
        padding: {S.XS}px;
        outline: none;
    }}

    /* 复选框 */
    QCheckBox {{
        color: {C.TEXT_PRIMARY};
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        spacing: {S.SM}px;
    }}

    QCheckBox::indicator {{
        width: 20px;
        height: 20px;
        border-radius: {R.SM}px;
        border: 2px solid {C.BORDER_DEFAULT};
        background-color: transparent;
    }}

    QCheckBox::indicator:hover {{
        border-color: {C.PRIMARY};
    }}

    QCheckBox::indicator:checked {{
        background-color: {C.PRIMARY};
        border-color: {C.PRIMARY};
    }}

    /* 单选框 */
    QRadioButton {{
        color: {C.TEXT_PRIMARY};
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        spacing: {S.SM}px;
    }}

    QRadioButton::indicator {{
        width: 18px;
        height: 18px;
        border-radius: 9px;
        border: 2px solid {C.BORDER_DEFAULT};
        background-color: transparent;
    }}

    QRadioButton::indicator:hover {{
        border-color: {C.PRIMARY};
    }}

    QRadioButton::indicator:checked {{
        background-color: {C.PRIMARY};
        border-color: {C.PRIMARY};
    }}

    /* 卡片容器 */
    QFrame[class="card"] {{
        background-color: {C.BG_CARD};
        border: 1px solid {C.BORDER_LIGHT};
        border-radius: {R.LG}px;
    }}

    /* 表格系统 */
    QTableWidget {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_LIGHT};
        border-radius: {R.LG}px;
        gridline-color: {C.BORDER_LIGHT};
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        outline: none;
    }}

    QTableWidget::item {{
        padding: {S.SM}px {S.MD}px;
        border-bottom: 1px solid {C.BORDER_LIGHT};
    }}

    QTableWidget::item:hover {{
        background-color: {C.PRIMARY_BG};
    }}

    QTableWidget::item:selected {{
        background-color: {C.PRIMARY_BG};
        color: {C.PRIMARY};
    }}

    QHeaderView::section {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_SECONDARY};
        padding: {S.SM}px {S.MD}px;
        border: none;
        border-bottom: 2px solid {C.BORDER_LIGHT};
        font-weight: {T.WEIGHT_SEMIBOLD};
        font-size: {T.SIZE_SM}px;
        font-family: {T.FONT_FAMILY};
    }}

    /* 滚动条 */
    QScrollBar:vertical {{
        background: transparent;
        width: 8px;
        margin: 0;
    }}

    QScrollBar::handle:vertical {{
        background: {C.GRAY_400}40;
        border-radius: 4px;
        min-height: 32px;
    }}

    QScrollBar::handle:vertical:hover {{
        background: {C.GRAY_500}60;
    }}

    QScrollBar:horizontal {{
        background: transparent;
        height: 8px;
        margin: 0;
    }}

    QScrollBar::handle:horizontal {{
        background: {C.GRAY_400}40;
        border-radius: 4px;
        min-width: 32px;
    }}

    QScrollBar::handle:horizontal:hover {{
        background: {C.GRAY_500}60;
    }}

    /* 滑块 */
    QSlider::groove:horizontal {{
        height: 4px;
        background: {C.BORDER_DEFAULT};
        border-radius: 2px;
    }}

    QSlider::handle:horizontal {{
        width: 16px;
        height: 16px;
        margin: -6px 0;
        background: {C.BG_CARD};
        border: 2px solid {C.PRIMARY};
        border-radius: 8px;
    }}

    QSlider::sub-page:horizontal {{
        background: {C.PRIMARY};
        border-radius: 2px;
    }}

    /* 数字输入框 */
    QSpinBox, QDoubleSpinBox {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_DEFAULT};
        border-radius: {R.MD}px;
        padding: {S.XS}px {S.SM}px;
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        min-height: 32px;
    }}

    QSpinBox:focus, QDoubleSpinBox:focus {{
        border: 2px solid {C.PRIMARY};
    }}

    /* 列表框 */
    QListWidget {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_LIGHT};
        border-radius: {R.LG}px;
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
        outline: none;
    }}

    QListWidget::item {{
        padding: {S.SM}px {S.MD}px;
        border-radius: {R.MD}px;
        margin: 2px 4px;
    }}

    QListWidget::item:hover {{
        background-color: {C.PRIMARY_BG};
    }}

    QListWidget::item:selected {{
        background-color: {C.PRIMARY_BG};
        color: {C.PRIMARY};
    }}

    /* 对话框 */
    QDialog {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border-radius: {R.LG}px;
    }}

    /* 工具提示 */
    QToolTip {{
        background-color: {C.GRAY_900};
        color: white;
        border: none;
        border-radius: {R.SM}px;
        padding: {S.XS}px {S.SM}px;
        font-size: {T.SIZE_XS}px;
        font-family: {T.FONT_FAMILY};
    }}

    /* 菜单栏 */
    QMenuBar {{
        background-color: {C.BG_TOOLBAR};
        color: {C.TEXT_PRIMARY};
        border-bottom: 1px solid {C.BORDER_LIGHT};
        font-family: {T.FONT_FAMILY};
        font-size: {T.SIZE_BASE}px;
    }}

    QMenuBar::item {{
        background-color: transparent;
        padding: {S.SM}px {S.MD}px;
        border-radius: {R.MD}px;
    }}

    QMenuBar::item:selected {{
        background-color: {C.PRIMARY_BG};
        color: {C.PRIMARY};
    }}

    /* 菜单 */
    QMenu {{
        background-color: {C.BG_CARD};
        color: {C.TEXT_PRIMARY};
        border: 1px solid {C.BORDER_LIGHT};
        border-radius: {R.MD}px;
        padding: {S.XS}px;
        font-family: {T.FONT_FAMILY};
    }}

    QMenu::item {{
        padding: {S.SM}px {S.MD}px;
        border-radius: {R.SM}px;
    }}

    QMenu::item:selected {{
        background-color: {C.PRIMARY_BG};
        color: {C.PRIMARY};
    }}

    QMenu::separator {{
        height: 1px;
        background: {C.BORDER_LIGHT};
        margin: {S.XS}px {S.SM}px;
    }}

    /* 标签页 */
    QTabWidget::pane {{
        border: 1px solid {C.BORDER_LIGHT};
        background-color: {C.BG_MAIN};
        border-radius: {R.LG}px;
    }}

    QTabBar::tab {{
        background-color: transparent;
        color: {C.TEXT_SECONDARY};
        padding: {S.SM}px {S.LG}px;
        margin-right: 2px;
        border-bottom: 2px solid transparent;
        font-weight: {T.WEIGHT_MEDIUM};
        font-size: {T.SIZE_BASE}px;
        font-family: {T.FONT_FAMILY};
    }}

    QTabBar::tab:hover {{
        color: {C.TEXT_PRIMARY};
    }}

    QTabBar::tab:selected {{
        color: {C.PRIMARY};
        border-bottom: 2px solid {C.PRIMARY};
    }}

    /* 进度条 */
    QProgressBar {{
        background-color: {C.BORDER_LIGHT};
        border: none;
        border-radius: 2px;
        height: 6px;
        text-align: center;
    }}

    QProgressBar::chunk {{
        background-color: {C.PRIMARY};
        border-radius: 2px;
    }}

    /* 分割线 */
    QFrame[frameShape="4"] {{
        border: none;
        border-top: 1px solid {C.BORDER_LIGHT};
    }}

    QFrame[frameShape="5"] {{
        border: none;
        border-left: 1px solid {C.BORDER_LIGHT};
    }}
    """


# 便捷函数(兼容旧代码)
def get_light_theme_styles():
    """获取浅色主题样式字典(向后兼容)"""
    from design_system import ColorPalette as C, TypographySystem as T
    return {
        "main_window": {
            "background_color": C.BG_MAIN,
            "color": C.TEXT_PRIMARY,
            "font_family": T.FONT_FAMILY
        },
        "button": {
            "background_color": C.PRIMARY,
            "color": "white",
            "border": "none",
            "font_weight": str(T.WEIGHT_MEDIUM),
            "font_size": f"{T.SIZE_BASE}px",
            "font_family": T.FONT_FAMILY
        }
    }


def generate_dynamic_styles(*args, **kwargs):
    """动态样式生成器(向后兼容)"""
    return generate_macos_theme()


def apply_app_style(app, *args, **kwargs):
    """为应用程序应用全局样式"""
    if app is None:
        from PyQt5.QtWidgets import QApplication
        app = QApplication.instance()

    if app is None:
        return

    style_sheet = generate_macos_theme()
    app.setStyleSheet(style_sheet)

    # 设置全局字体
    from PyQt5.QtGui import QFont
    font = app.font()
    font.setFamily(TypographySystem.FONT_FAMILY)
    font.setPointSize(TypographySystem.SIZE_BASE)
    app.setFont(font)
